#use_frameworks!
use_modular_headers!
target 'BGSocialLogin_Example' do
  
  pod 'BGSocialLogin', :path => '../'
  pod 'Toaster'
end

pre_install do |installer|
  def installer.verify_no_static_framework_transitive_dependencies; end
end
